/*

 DUDE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 2 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char dude[] =
{
  0x07,0x07,0x05,0x06,0x07,0x00,0x1F,0x17,
  0x33,0x33,0x33,0x33,0x03,0x03,0x03,0x07,
  0xF8,0x58,0xF8,0x18,0xF8,0xC0,0xFE,0xFA,
  0xF3,0xF3,0xF3,0xF3,0xF0,0x30,0x30,0x38
};

/* End of DUDE.C */
